# Generated by Django 3.1.7 on 2021-03-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('front', 'front'), ('back', 'back'), ('framework', 'framework')], max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to='static/media/blog')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.EmailField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
